version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
